
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      # serviceAccountName: example-crud
      containers:
      - name: hello
        image: gcr.io/google-samples/hello-app:1.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
        imagePullPolicy: Always
        ports:
        - containerPort: 8080