kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-crud-demo-storage-class
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-example-crud-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: example-crud-demo-storage-class
  resources:
    requests:
      storage: 5Gi